# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ devel ]
    paths-ignore:
      - 'docs/**'
      - 'bin/**'
      - 'LICENSE'
      - '**.md'
  pull_request:
    branches: [ devel ]
    paths-ignore:
      - 'docs/**'
      - 'bin/**'
      - 'LICENSE'
      - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - 
      uses: actions/checkout@v3

     - 
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'stable' # default is 'stable'
     - 
      run: nimble depends     
     - 
      run: nim c bot.nim
